# ==================== APLICACIÓN ====================
spring.application.name=ms-andesstay-reservations

# ==================== BASE DE DATOS (MongoDB Atlas) ====================
spring.data.mongodb.uri=mongodb+srv://alonvergara_db_user:4WjTvKSAw1RhdIpz@cluster0.vzgnvfr.mongodb.net/andesstay_reservations?retryWrites=true&w=majority

# ==================== SEGURIDAD (JWT Azure AD) ====================
# En produccion, descomenta y reemplaza por el issuer real de Azure AD.
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/TU_TENANT_ID/v2.0

# ==================== SERVIDOR ====================
server.port=8081

# ==================== ACTUATOR ====================
management.endpoints.web.exposure.include=health,info